# Generated by Django 4.2.2 on 2023-06-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='owner',
            new_name='user',
        ),
    ]
